<Project Sdk="Microsoft.NET.Sdk">
    <!--Core DLL Properties-->
    <PropertyGroup>
        <TargetFrameworks>netframework4.7.2</TargetFrameworks>
        <RuntimeIdentifiers>win-x64;win-x86;win-arm64;linux-x64;linux-arm;linux-arm64;linux-musl-x64;linux-musl-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
        <AssemblyName>JSON Loader v3</AssemblyName>
        <Description>This is the new Modulated and API Based system in which JSONLoader will run off of (and maybe a CSV loader too)</Description>
        <Version>3.0.0</Version>
        <Authors>Chaosyr</Authors>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>Latest</LangVersion>
        <RootNamespace>JSONLoader3</RootNamespace>
        <NoWarn>$(NoWarn);AD0001;CS0612;CS0618;Publicizer001</NoWarn>
        <SelfContained>true</SelfContained>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <!--NUGET Dependencies-->
    <ItemGroup>
        <PackageReference Include="API_dev-API" Version="2.24.0" />
        <PackageReference Include="BepInEx.Analyzers" Version="1.0.8" PrivateAssets="all" />
        <PackageReference Include="BepInEx.Core" Version="5.4.21" />
        <PackageReference Include="Cecil.ANSI_Utils" Version="2.0.0" />
        <PackageReference Include="UnityEngine.Modules" Version="2019.4.24" IncludeAssets="compile" />
        <PackageReference Include="Inscryption.GameLibs" Version="1.9.0-r.0" />
    </ItemGroup>

    <!--Net Framework References-->
    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
    </ItemGroup>

    <!--Local DLL Dependencies-->
    <ItemGroup>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Cores\CSVLoaderV1Support\Schemas\" />
      <Folder Include="Cores\JSONLoaderV2Support\Schemas\" />
      <Folder Include="Cores\JSONLoaderV3Support\Schemas\" />
      <Folder Include="Peripheral\CSV_LINT\" />
      <Folder Include="Peripheral\CSV_SCHEMA\" />
    </ItemGroup>

    <!--Cleanup Publish for our Build System-->
    <Target Name="StripAllNuGetFromPublish" AfterTargets="ComputeFilesToPublish">
        <ItemGroup>
            <ResolvedFileToPublish Remove="@(ResolvedFileToPublish)" Condition="'%(ResolvedFileToPublish.Extension)' == '.dll' and '%(ResolvedFileToPublish.RelativePath)' != 'JSONLoader.dll'" />
        </ItemGroup>
    </Target>

    <!--Build System Properties-->
    <PropertyGroup>
        <!--Copy Locations-->
        <BuildCopyLocations>Thunderstore-Package-Elements</BuildCopyLocations>
        <CHANGELOGCopyLocation>CHANGELOG.md</CHANGELOGCopyLocation>
        <READMECopyLocation>README.md</READMECopyLocation>
        <LICENSECopyLocation>LICENSE.md</LICENSECopyLocation>
        <ReleaseMode>Prerelease</ReleaseMode>
        <!--Thunderstore Manifest Properties-->
        <ThunderstorePackageName>JSON_and_CSV_Loader_Nightly</ThunderstorePackageName>
        <ThunderstorePackageVersion>0.0.3</ThunderstorePackageVersion>
        <ThunderstoreWebsiteURL>https://github.com/MADH95/JSONLoader/tree/Refactor-JSONLoader-3</ThunderstoreWebsiteURL>
        <ThunderstorePackageDescription>This is the Nightly version of JSONLoader, this is effectively a preview of whats to come to JSONLoader (and CSVLoader).</ThunderstorePackageDescription>
        <ThunderstorePackageDependencyStrings>BepInEx-BepInExPack_Inscryption-5.4.2305;BepInEx-MonoMod_Loader_Inscryption-1.0.0;API_dev-API-2.24.0;Cecil_Libraries_Organization-Cecil_Libraries_Package-1.0.1;Stoat_Games-ANSI_Mod-2.0.1</ThunderstorePackageDependencyStrings>
    </PropertyGroup>
</Project>